### PR TITLE
Reconciliation Service API

### PR DESCRIPTION
**Pull request by awagner-mainz**
API spec: https://reconciliation-api.github.io/specs/latest/
W3C Community Group: https://www.w3.org/community/reconciliation/ (Some of them are the same people who run lobid at HBZ NRW)

The API is based on OpenRefine's reconciliation function and provides some additional functions such as type-ahead suggestions and more. There is a list of platforms who run a Reconciliation Service API endpoint at https://reconciliation-api.github.io/testbench/.

The Reconciliation Service connector can be used like this:
`<pb-authority connector="ReconciliationService" name="term" prefix="wd" endpoint="https://wikidata.reconci.link/api" debug="debug"/>`

In other words, you define the `endpoint` and a `prefix` and that's it. The `debug` switch gives diagnostic output in the browser console and can be left away. I have tested several lookup providers and it worked well.

Some observations, if these indicate that the request has to be improved before it can be merged, I'd be grateful for some helpful pointers:
- Maybe it'd need a better handling of no good responses - the progress bar of `annotate.html` was running and I wasn't sure if the query would take a long time or if this was already the "no results" situation...
- Also, I could not get it to work inside a custom connector (the lookup worked, but it did not create the register.xml file or, when I copied this over from the playground app, entries within it). Suggestions welcome...
- Finally, I was not sure what information the `strings` key of a result map would have to be filled with, so I left it away. (I piped some information about the type of entity of a result into the `details` key.) 

I have tested like this:

annotate.html:
```
...
    <main>
        <aside class="annotation-editor">
            <div class="toolbar">
                <paper-icon-button id="clear-all" icon="icons:refresh"/>
                <paper-icon-button class="annotation-action authority" data-i18n="[title]annotations.place" title="Place" data-type="place" icon="maps:place" data-shortcut="⌘+⇧+q,ctrl+⇧+q" disabled="disabled"/>

<!-- *** Test here *** -->
                <paper-icon-button class="annotation-action authority" data-i18n="[title]annotations.term1" title="Term1" data-type="term1" icon="icons:loyalty" data-shortcut="⌘+⇧+q,ctrl+⇧+q" disabled="disabled"/>
                <paper-icon-button class="annotation-action authority" data-i18n="[title]annotations.term2" title="Term2" data-type="term2" icon="icons:loyalty" data-shortcut="⌘+⇧+q,ctrl+⇧+q" disabled="disabled"/>
                <paper-icon-button class="annotation-action authority" data-i18n="[title]annotations.term3" title="Term3" data-type="term3" icon="icons:loyalty" data-shortcut="⌘+⇧+q,ctrl+⇧+q" disabled="disabled"/>
                <paper-icon-button class="annotation-action authority" data-i18n="[title]annotations.term5" title="Term5" data-type="term5" icon="icons:loyalty" data-shortcut="⌘+⇧+q,ctrl+⇧+q" disabled="disabled"/>
                <paper-icon-button class="annotation-action authority" data-i18n="[title]annotations.term9" title="Term9" data-type="term9" icon="icons:loyalty" data-shortcut="⌘+⇧+q,ctrl+⇧+q" disabled="disabled"/>
                <paper-icon-button class="annotation-action authority" data-i18n="[title]annotations.term0" title="Term0" data-type="term0" icon="icons:loyalty" data-shortcut="⌘+⇧+q,ctrl+⇧+q" disabled="disabled"/>
<!-- *** End test *** -->

                <paper-icon-button class="annotation-action authority" data-i18n="[title]annotations.term" title="Term" data-type="term" icon="icons:bookmark" data-shortcut="⌘+⇧+t,ctrl+⇧+t" disabled="disabled"/>
                <paper-icon-button class="annotation-action" data-i18n="[title]annotations.modify" title="Edit" data-type="edit" icon="editor:mode-edit" data-shortcut="⌘+⇧+m,ctrl+⇧+m" disabled="disabled"/>
            </div>

... and further down ...

    <paper-dialog id="authority-dialog">
        <paper-dialog-scrollable>
            <pb-authority-lookup subscribe="transcription" emit="transcription">

<!-- *** Test here *** -->
                <pb-authority connector="ReconciliationService" name="term1" prefix="gtn" endpoint="https://services.getty.edu/vocab/reconcile/" debug="debug"/>
                <pb-authority connector="ReconciliationService" name="term2" prefix="wd" endpoint="https://wikidata.reconci.link/api" debug="debug"/>
                <pb-authority connector="ReconciliationService" name="term3" prefix="lobid" endpoint="https://lobid.org/gnd/reconcile" debug="debug"/>
                <pb-authority connector="ReconciliationService" name="term5" prefix="bbl" endpoint="https://data.biblissima.fr/api/reconcile" debug="debug"/>
                <pb-authority connector="ReconciliationService" name="term9" prefix="bhm" endpoint="https://aleph.occrp.org/api/2/collections/276/reconcile" debug="debug"/>
                <pb-authority connector="Custom" name="term0">
                    <pb-authority connector="ReconciliationService" prefix="custom" endpoint="https://lobid.org/gnd/reconcile" debug="debug"/>
                </pb-authority>
<!-- *** End test *** -->

                <pb-authority connector="Custom" name="organization">
                    <pb-authority connector="GND" prefix="gnd"/>
                </pb-authority>
            </pb-authority-lookup>
```

### CODE REVIEW

**Comment by awagner-mainz** [comment]
As I wrote in the slack channel, I guess I have to think this through a bit more thoroughly: From the developers' point of view, we cannot know what type of entity is reconciled by a reconc service configured by the user, so we don't know what the fields will be and what the best structure to store them in the local registry.xml file in the case of the custom connector is.
(Possibly necessary changes involve not only this pb-component's reconcile.js file, but also modifications/extensions to tei-publisher's annotation-config.xql , annotation.xql or annotation.js ...)

Here is the current `getRecord()`/custom connector situation:

For the lobid/gnd reconciliation service, the getRecord() function relies on the service's "view template" and returns an object like this one:

```json
{
	"professionOrOccupation": [
	  {
		"id": "https://d-nb.info/gnd/4040841-3",
		"label": "Musiker"
	  },
	  {
		"id": "https://d-nb.info/gnd/4362006-1",
		"label": "Bassist <Sänger>"
	  },
	  {
		"id": "https://d-nb.info/gnd/4124099-6",
		"label": "Sänger"
	  },
	  {
		"id": "https://d-nb.info/gnd/4140880-9",
		"label": "Musiklehrer"
	  },
	  {
		"id": "https://d-nb.info/gnd/4398802-7",
		"label": "Kapellmeister"
	  }
	],
	"gender": [
	  {
		"id": "https://d-nb.info/standards/vocab/gnd/gender#notKnown",
		"label": "Unbekannt"
	  }
	],
	"variantNameEntityForThePerson": [
	  {
		"nameAddition": [
		  "von Khenua"
		],
		"personalName": [
		  "Richart"
		]
	  },
	  {
		"personalName": [
		  "Ricardus"
		]
	  },
	  {
		"nameAddition": [
		  "von Genua"
		],
		"personalName": [
		  "Richard"
		]
	  }
	],
	"type": [
	  "DifferentiatedPerson",
	  "AuthorityResource",
	  "Person"
	],
	"@context": "http://lobid.org/gnd/context.jsonld",
	"gndSubjectCategory": [
	  {
		"id": "https://d-nb.info/standards/vocab/gnd/gnd-sc#14.4p",
		"label": "Personen zu Musik"
	  }
	],
	"oldAuthorityNumber": [
	  "(DE-588a)136318347"
	],
	"geographicAreaCode": [
	  {
		"id": "https://d-nb.info/standards/vocab/gnd/geographic-area-code#XA-DE",
		"label": "Deutschland"
	  }
	],
	"periodOfActivity": [
	  "1563-1574"
	],
	"describedBy": {
	  "id": "https://d-nb.info/gnd/136318347/about",
	  "license": {
		"id": "http://creativecommons.org/publicdomain/zero/1.0/",
		"label": "http://creativecommons.org/publicdomain/zero/1.0/"
	  },
	  "dateModified": "2021-01-08T10:18:56.000"
	},
	"gndIdentifier": "136318347",
	"id": "https://d-nb.info/gnd/136318347",
	"placeOfActivity": [
	  {
		"id": "https://d-nb.info/gnd/4127793-4",
		"label": "München"
	  }
	],
	"preferredName": "Richart",
	"variantName": [
	  "Richart, von Khenua",
	  "Ricardus",
	  "Richard, von Genua"
	],
	"preferredNameEntityForThePerson": {
	  "personalName": [
		"Richart"
	  ]
	},
	"sameAs": [
	  {
		"collection": {
		  "abbr": "DE-M512",
		  "name": "Bayerisches Musiker-Lexikon Online",
		  "publisher": "Bayerisches Musiker-Lexikon Online",
		  "icon": "http://bmlo.de/x/pic/favicon.gif",
		  "id": "http://bmlo.de"
		},
		"id": "http://bmlo.de/Q/GND=136318347"
	  },
	  {
		"id": "http://viaf.org/viaf/67152742897727731118",
		"collection": {
		  "id": "http://www.wikidata.org/entity/Q54919",
		  "abbr": "VIAF",
		  "publisher": "OCLC",
		  "icon": "http://viaf.org/viaf/images/viaf.ico",
		  "name": "Virtual International Authority File (VIAF)"
		}
	  },
	  {
		"collection": {
		  "abbr": "DNB",
		  "name": "Gemeinsame Normdatei (GND) im Katalog der Deutschen Nationalbibliothek",
		  "publisher": "Deutsche Nationalbibliothek",
		  "icon": "https://www.dnb.de/SiteGlobals/Frontend/DNBWeb/Images/favicon.png?__blob=normal&v=4",
		  "id": "http://www.wikidata.org/entity/Q36578"
		},
		"id": "https://d-nb.info/gnd/136318347/about"
	  },
	  {
		"collection": {
		  "abbr": "DDB",
		  "name": "Deutsche Digitale Bibliothek",
		  "publisher": "Deutsche Digitale Bibliothek",
		  "icon": "https://www.deutsche-digitale-bibliothek.de/favicon.ico",
		  "id": "http://www.wikidata.org/entity/Q621630"
		},
		"id": "https://www.deutsche-digitale-bibliothek.de/person/gnd/136318347"
	  }
	]
  }
```

And then a POST request goes to `https://...:8443/exist/apps/project-name/api/register/term0/custom-136318347` with this body:

```json
{
    "professionOrOccupation": [
        {
            "id": "https://d-nb.info/gnd/4040841-3",
            "label": "Musiker"
        },
        {
            "id": "https://d-nb.info/gnd/4362006-1",
            "label": "Bassist <Sänger>"
        },
        {
            "id": "https://d-nb.info/gnd/4124099-6",
            "label": "Sänger"
        },
        {
            "id": "https://d-nb.info/gnd/4140880-9",
            "label": "Musiklehrer"
        },
        {
            "id": "https://d-nb.info/gnd/4398802-7",
            "label": "Kapellmeister"
        }
    ],
    "gender": [
        {
            "id": "https://d-nb.info/standards/vocab/gnd/gender#notKnown",
            "label": "Unbekannt"
        }
    ],
    "variantNameEntityForThePerson": [
        {
            "nameAddition": [
                "von Khenua"
            ],
            "personalName": [
                "Richart"
            ]
        },
        {
            "personalName": [
                "Ricardus"
            ]
        },
        {
            "nameAddition": [
                "von Genua"
            ],
            "personalName": [
                "Richard"
            ]
        }
    ],
    "type": [
        "DifferentiatedPerson",
        "AuthorityResource",
        "Person"
    ],
    "@context": "http://lobid.org/gnd/context.jsonld",
    "gndSubjectCategory": [
        {
            "id": "https://d-nb.info/standards/vocab/gnd/gnd-sc#14.4p",
            "label": "Personen zu Musik"
        }
    ],
    "oldAuthorityNumber": [
        "(DE-588a)136318347"
    ],
    "geographicAreaCode": [
        {
            "id": "https://d-nb.info/standards/vocab/gnd/geographic-area-code#XA-DE",
            "label": "Deutschland"
        }
    ],
    "periodOfActivity": [
        "1563-1574"
    ],
    "describedBy": {
        "id": "https://d-nb.info/gnd/136318347/about",
        "license": {
            "id": "http://creativecommons.org/publicdomain/zero/1.0/",
            "label": "http://creativecommons.org/publicdomain/zero/1.0/"
        },
        "dateModified": "2021-01-08T10:18:56.000"
    },
    "gndIdentifier": "136318347",
    "id": "https://d-nb.info/gnd/136318347",
    "placeOfActivity": [
        {
            "id": "https://d-nb.info/gnd/4127793-4",
            "label": "München"
        }
    ],
    "preferredName": "Richart",
    "variantName": [
        "Richart, von Khenua",
        "Ricardus",
        "Richard, von Genua"
    ],
    "preferredNameEntityForThePerson": {
        "personalName": [
            "Richart"
        ]
    },
    "sameAs": [
        {
            "collection": {
                "abbr": "DE-M512",
                "name": "Bayerisches Musiker-Lexikon Online",
                "publisher": "Bayerisches Musiker-Lexikon Online",
                "icon": "http://bmlo.de/x/pic/favicon.gif",
                "id": "http://bmlo.de"
            },
            "id": "http://bmlo.de/Q/GND=136318347"
        },
        {
            "id": "http://viaf.org/viaf/67152742897727731118",
            "collection": {
                "id": "http://www.wikidata.org/entity/Q54919",
                "abbr": "VIAF",
                "publisher": "OCLC",
                "icon": "http://viaf.org/viaf/images/viaf.ico",
                "name": "Virtual International Authority File (VIAF)"
            }
        },
        {
            "collection": {
                "abbr": "DNB",
                "name": "Gemeinsame Normdatei (GND) im Katalog der Deutschen Nationalbibliothek",
                "publisher": "Deutsche Nationalbibliothek",
                "icon": "https://www.dnb.de/SiteGlobals/Frontend/DNBWeb/Images/favicon.png?__blob=normal&v=4",
                "id": "http://www.wikidata.org/entity/Q36578"
            },
            "id": "https://d-nb.info/gnd/136318347/about"
        },
        {
            "collection": {
                "abbr": "DDB",
                "name": "Deutsche Digitale Bibliothek",
                "publisher": "Deutsche Digitale Bibliothek",
                "icon": "https://www.deutsche-digitale-bibliothek.de/favicon.ico",
                "id": "http://www.wikidata.org/entity/Q621630"
            },
            "id": "https://www.deutsche-digitale-bibliothek.de/person/gnd/136318347"
        }
    ]
}
```

But this requests results in a 500 Error:

```
description	"exerr:ERROR Content for update is empty. [at line 52, column 17, source: /db/apps/metallindustrie/modules/lib/api/annotations.xql]
In function:
	anno:save-local-copy(map(*)) [176:30:/db/apps/metallindustrie/modules/lib/api/annotations.xql]. Content for update is empty.
	[at line 52 of /db/apps/metallindustrie/modules/lib/api/annotations.xql]"
```


Or, with the wikidata service, where the "view template" gives no json but html and we have to rely on the reconc. query itself, the `getRequest` returns this:

```json
{
  "register": "termA",
  "id": "custom-Q2795",
  "label": "Chemnitz",
  "link": "https://www.wikidata.org/wiki/Q2795",
  "details": "big city, major regional center, urban district in Saxony, urban municipality of Germany",
  "provider": "ReconciliationService"
}
```

And then a POST request goes to `https://...:8443/exist/apps/project-name/api/register/termA/custom-Q2795` with this body:

```json
{
    "register": "termA",
    "id": "custom-Q2795",
    "label": "Chemnitz",
    "link": "https://www.wikidata.org/wiki/Q2795",
    "details": "big city, major regional center, urban district in Saxony, urban municipality of Germany",
    "provider": "ReconciliationService"
}
```

And the response from the register api is just the same as in the case before...

**Comment by wolfgangmm** [comment]
I think we should leave out the custom connector and get the PR merged. It's a welcome addition for many users, even without the possibility to overwrite entries via the custom connector.

Could you rebase your branch for the merge?

**Comment by awagner-mainz** [comment]
Thank you, it should be done (i.e. rebased) now.

**Comment by awagner-mainz** [comment]
... or maybe I did something wrong when rebasing - I wonder why it says 14 files are different. It should be only 2 files: ` src/authority/{connectors.js,reconciliation.js}` and in `connectors.js` one of the changes is not mine but coming from the `master` branch. (I have not filed many pull requests before, none where there was rebasing involved.)

**Comment by wolfgangmm** [comment]
It looks like you did not really `git rebase master` but maybe a merge instead? After a rebase, your commits should be applied on top of those coming from master.

**Comment by awagner-mainz** [comment]
I am quite sure I did a rebase, but during the process something was odd indeed and I had to merge more than I expected. I guess at some point I did something in the wrong order. Shall I now do something more? I could throw away my current reconciliation branch and re-apply my changes to a new, pristine fork from origin.

I am sorry for the chaos.

**Comment by wolfgangmm** [comment]
If you can roll back to the state before the attempted rebase, you could probably just redo it and force-push. Otherwise opening a new PR is an option too.

**Comment by awagner-mainz** [comment]
I will close this and try with a new PR...

**Pull request closed without merging**
