### PR TITLE
fixes unwanted null values with multiple select

### PR DESCRIPTION
**Pull request by JoernT**
when selecting values from pb-select multiple an unwanted 'null' value was created in formData.

Using 'undefined' instead fixes the issue.

### CODE REVIEW

**Comment by tuurma** [comment]
don't know how to do that now but commit messages need to follow certain convention now to be picked up correctly for automated release, so yours should read something like: `fix(pb-select) fixes unwanted null values with multiple select`

**Comment by tuurma** [comment]
don't know how to do that now but commit messages need to follow certain convention now to be picked up correctly for automated release, so yours should read something like: `fix(pb-select) fixes unwanted null values with multiple select`

**Comment by tuurma** [comment]
don't know how to do that now but commit messages need to follow certain convention now to be picked up correctly for automated release, so yours should read something like: `fix(pb-select) fixes unwanted null values with multiple select`

**Comment by JoernT** [comment]
ah thanks - forgot about that

**Comment by JoernT** [comment]
i'll redo it

**Pull request closed without merging**
